
import RPi.GPIO as GPIO


GPIO.setmode(GPIO.BCM)
GPIO.setup(0,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(1,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(2,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(3,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(4,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(5,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(6,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(7,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(8,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(9,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(10,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(11,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(12,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(13,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(14,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(15,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(16,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(17,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(18,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(19,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(20,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(21,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(22,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(23,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(24,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(25,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(26,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(27,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)


print('tes')
print("PIN 0 Status = ",GPIO.input(0))
print("PIN 1 Status = ",GPIO.input(1))
print("PIN 2 Status = ",GPIO.input(2))
print("PIN 3 Status = ",GPIO.input(3))
print("PIN 4 Status = ",GPIO.input(4))
print("PIN 5 Status = ",GPIO.input(5))
print("PIN 6 Status = ",GPIO.input(6))
print("PIN 7 Status = ",GPIO.input(7))
print("PIN 8 Status = ",GPIO.input(8))
print("PIN 9 Status = ",GPIO.input(9))
print("PIN 10 Status = ",GPIO.input(10))
print("PIN 11 Status = ",GPIO.input(11))
print("PIN 12 Status = roda 4 ",GPIO.input(12))
print("PIN 13 Status = ",GPIO.input(13))
print("PIN 14 Status = ",GPIO.input(14))
print("PIN 15 Status = ",GPIO.input(15))
print("PIN 16 Status = cran atau alat berat",GPIO.input(16))
print("PIN 17 Status = alat berat rantai",GPIO.input(17))
print("PIN 18 Status = ",GPIO.input(18))
print("PIN 19 Status = ",GPIO.input(19))
print("PIN 20 Status = truck dan trailler",GPIO.input(20))
print("PIN 21 Status = roda 6/lebih",GPIO.input(21))
print("PIN 22 Status = ",GPIO.input(22))
print("PIN 23 Status = ",GPIO.input(23))
print("PIN 24 Status = ",GPIO.input(24))
print("PIN 25 Status = ",GPIO.input(25))
print("PIN 26 Status = ",GPIO.input(26))
print("PIN 27 Status = forklip ",GPIO.input(27))

